---
- name: Download Vector package
  ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
      dest: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
      mode: '0644'
- name: Install Vector package
  become: true
  ansible.builtin.yum:
    name: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
    disable_gpg_check: true
- name: Deploy Vector configuration
  become: true
  ansible.builtin.template:
    src: templates/vector.yaml.j2
    dest: /etc/vector/vector.yaml
    mode: '0644'
  notify:
        - Restart vector
- name: Remove downloaded Vector package
  become: true
  ansible.builtin.file:
    path: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
    state: absent
- name: Remove downloaded Vector package
  become: true
  ansible.builtin.file:
    path: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
    state: absent